apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deletion
  name: marketplace-be-deletion
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deletion
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deletion
    spec:
      containers:
      - image: 192.168.110.135:5000/deletion:711
        name: deletion
